# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ReinsHook < Formula
  desc "Pairs a phone with this Mac over SSH and serves the Reins loopback gateway"
  homepage "https://github.com/EndersonPro/reins"
  version "0.11.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/EndersonPro/homebrew-reins/releases/download/v0.11.0/reins-hook_Darwin_x86_64.tar.gz"
      sha256 "a27a76cf5b501823d2a776c2888241aadfdb1fa5d44244f1a30c71c1187fc30c"

      define_method(:install) do
        bin.install "reins-hook"
        prefix.install "THIRD_PARTY_NOTICES.md"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/EndersonPro/homebrew-reins/releases/download/v0.11.0/reins-hook_Darwin_arm64.tar.gz"
      sha256 "6d150f9cf98c418dbe684277ea76aea62e4075ee92a0d895cadd3c8aa0fd17f2"

      define_method(:install) do
        bin.install "reins-hook"
        prefix.install "THIRD_PARTY_NOTICES.md"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/EndersonPro/homebrew-reins/releases/download/v0.11.0/reins-hook_Linux_x86_64.tar.gz"
      sha256 "230b5023ea8d63cab78fd662159c5ea3258e68a3bec529ff54321842bd62bd52"
      define_method(:install) do
        bin.install "reins-hook"
        prefix.install "THIRD_PARTY_NOTICES.md"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/EndersonPro/homebrew-reins/releases/download/v0.11.0/reins-hook_Linux_arm64.tar.gz"
      sha256 "af2962767bc7bb3649b795fe48e4004348f7e5a26288c706dc470f4f984a001f"
      define_method(:install) do
        bin.install "reins-hook"
        prefix.install "THIRD_PARTY_NOTICES.md"
      end
    end
  end

  def caveats
    <<~EOS
      Get started:
        reins-hook setup
        reins-hook install
        reins-hook serve
    EOS
  end

  service do
    run [opt_bin/"reins-hook", "serve"]
    keep_alive true
    log_path var/"log/reins-hook.log"
    error_log_path var/"log/reins-hook.log"
    # brew services runs this under launchd with a minimal PATH
    # (/usr/bin:/bin:/usr/sbin:/sbin), so adb/herdr/tmux resolved via
    # exec.LookPath at runtime silently fail even though they're on the
    # user's interactive shell PATH. Extend it with the locations those
    # tools commonly live in.
    environment_variables PATH: std_service_path_env + ":#{Dir.home}/.local/bin:#{Dir.home}/Library/Android/sdk/platform-tools"
  end

  test do
    system "#{bin}/reins-hook", "version"
  end
end
