# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ReinsHook < Formula
  desc "Pairs a phone with this Mac over SSH and serves the Reins loopback gateway"
  homepage "https://github.com/EndersonPro/reins"
  version "0.10.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/EndersonPro/homebrew-reins/releases/download/v0.10.0/reins-hook_Darwin_x86_64.tar.gz"
      sha256 "3faa8684e8536055454f293ba402cae78636ef72788401c4ee7db89eddc01549"

      define_method(:install) do
        bin.install "reins-hook"
        prefix.install "THIRD_PARTY_NOTICES.md"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/EndersonPro/homebrew-reins/releases/download/v0.10.0/reins-hook_Darwin_arm64.tar.gz"
      sha256 "dabc46b7eca976b1033255714ddabf28df00406e443b45afbf88e83c379fdcb1"

      define_method(:install) do
        bin.install "reins-hook"
        prefix.install "THIRD_PARTY_NOTICES.md"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/EndersonPro/homebrew-reins/releases/download/v0.10.0/reins-hook_Linux_x86_64.tar.gz"
      sha256 "f7960ae16d5ced6f84313e4aa159a5acd64a9ad478f0908dd04c75451c5d4e80"
      define_method(:install) do
        bin.install "reins-hook"
        prefix.install "THIRD_PARTY_NOTICES.md"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/EndersonPro/homebrew-reins/releases/download/v0.10.0/reins-hook_Linux_arm64.tar.gz"
      sha256 "c2ac43cd801792ae86e41c6696d9fcbf66505398fd8c0d4d0f42687495e40c13"
      define_method(:install) do
        bin.install "reins-hook"
        prefix.install "THIRD_PARTY_NOTICES.md"
      end
    end
  end

  def caveats
    <<~EOS
      Get started:
        reins-hook setup
        reins-hook install
        reins-hook serve
    EOS
  end

  service do
    run [opt_bin/"reins-hook", "serve"]
    keep_alive true
    log_path var/"log/reins-hook.log"
    error_log_path var/"log/reins-hook.log"
    # brew services runs this under launchd with a minimal PATH
    # (/usr/bin:/bin:/usr/sbin:/sbin), so adb/herdr/tmux resolved via
    # exec.LookPath at runtime silently fail even though they're on the
    # user's interactive shell PATH. Extend it with the locations those
    # tools commonly live in.
    environment_variables PATH: std_service_path_env + ":#{Dir.home}/.local/bin:#{Dir.home}/Library/Android/sdk/platform-tools"
  end

  test do
    system "#{bin}/reins-hook", "version"
  end
end
