# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ReinsHook < Formula
  desc "Pairs a phone with this Mac over SSH and serves the Reins loopback gateway"
  homepage "https://github.com/EndersonPro/reins"
  version "0.1.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/EndersonPro/homebrew-reins/releases/download/v0.1.0/reins-hook_Darwin_x86_64.tar.gz"
      sha256 "e92f96d6aca27710e527d8c62508538c8008bf2acbc0ac6b656fdcfb7f4e4b9e"

      define_method(:install) do
        bin.install "reins-hook"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/EndersonPro/homebrew-reins/releases/download/v0.1.0/reins-hook_Darwin_arm64.tar.gz"
      sha256 "df19b9ba33ebc0d1823c95fdc3a464b6c5307132c8904a74681c92495e7ae6f7"

      define_method(:install) do
        bin.install "reins-hook"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/EndersonPro/homebrew-reins/releases/download/v0.1.0/reins-hook_Linux_x86_64.tar.gz"
      sha256 "fded6406b459934a26cb36708116d727a908a5777122bcc8cce88d9e4613b6e9"
      define_method(:install) do
        bin.install "reins-hook"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/EndersonPro/homebrew-reins/releases/download/v0.1.0/reins-hook_Linux_arm64.tar.gz"
      sha256 "27682ba562005fc49cb301aeb6b372bb250a161951b5e55c0613fc123394ae3b"
      define_method(:install) do
        bin.install "reins-hook"
      end
    end
  end

  def caveats
    <<~EOS
      Get started:
        reins-hook setup
        reins-hook install
        reins-hook serve
    EOS
  end

  service do
    run [opt_bin/"reins-hook", "serve"]
    keep_alive true
    log_file var/"log/reins-hook.log"
    error_log_file var/"log/reins-hook.log"
  end

  test do
    system "#{bin}/reins-hook", "version"
  end
end
